=== shield-h2020/dashboard/backend/dare/schema/mspl.xsd
<?xml version="1.0" encoding="UTF-8"?><!--Copyright 2017 Politecnico di TorinoLicensed under the Apache License, Version 2.0 (the "License");you may not use this file except in compliance with the License.You may obtain a copy of the License at    http://www.apache.org/licenses/LICENSE-2.0Unless required by applicable law or agreed to in writing, softwaredistributed under the License is distributed on an "AS IS" BASIS,WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.See the License for the specific language governing permissions andlimitations under the License. --><schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://security.polito.it/shield/mspl" xmlns:tns="http://security.polito.it/shield/mspl"	elementFormDefault="qualified">	<element name="recommendations" type="tns:recommendations">		<annotation>			<documentation>The root element. A set of suggested MSPL sets.</documentation>		</annotation>	</element>	<complexType name="recommendations">		<annotation>			<documentation>The root element. A set of suggested MSPL sets.</documentation>		</annotation>		<sequence>			<element name="mspl-set" type="tns:mspl-set" maxOccurs="unbounded" minOccurs="1"/>		</sequence>	</complexType>	<complexType name="mspl-set">		<sequence>			<annotation>				<documentation>The root element. A set of configurations.</documentation>			</annotation>			<element name="context" type="tns:context" />			<element name="it-resource" type="tns:it-resource" maxOccurs="unbounded" minOccurs="1" />		</sequence>	</complexType>	<complexType name="context">		<annotation>			<documentation>The information about the attack.</documentation>		</annotation>		<sequence>			<element name="severity" type="positiveInteger">				<annotation>					<documentation>The attack severity.</documentation>				</annotation>			</element>			<element name="type">				<annotation>					<documentation>The attack type.</documentation>				</annotation>				<simpleType>					<restriction base="string">						<enumeration value="DoS" />						<enumeration value="DNS tunneling" />						<enumeration value="Cryptomining" />						<enumeration value="Worm" /><enumeration value="slowloris" /><enumeration value="Slowloris" /><enumeration value="wannacry" /><enumeration value="Wannacry" /> <enumeration value="Cryptocurrency Mining" />					</restriction>				</simpleType>			</element>			<element name="timestamp" type="dateTime">				<annotation>					<documentation>The attack timestamp.</documentation>				</annotation>			</element>		</sequence>	</complexType>	<complexType name="it-resource">		<sequence>			<element maxOccurs="unbounded" minOccurs="1" name="configuration" type="tns:configuration">				<annotation>					<documentation>A physical or virtual device that needs to be configured.</documentation>				</annotation>			</element>		</sequence>		<attribute use="required" name="id" type="string">			<annotation>				<documentation>The identifier of the resource.</documentation>			</annotation>		</attribute>	</complexType>	<complexType name="configuration" />	<complexType name="filtering-configuration">		<annotation>			<documentation>A configuration for an IT resource.</documentation>		</annotation>		<complexContent>			<extension base="tns:configuration">				<sequence>					<element maxOccurs="1" minOccurs="0" name="default-action" type="tns:filtering-action">						<annotation>							<documentation>The default action.</documentation>						</annotation>					</element>					<element maxOccurs="1" minOccurs="0" name="resolution-strategy" type="tns:resolution-strategy">						<annotation>							<documentation>The resolution strategy.</documentation>						</annotation>					</element>					<element maxOccurs="unbounded" minOccurs="0" name="rule" type="tns:filtering-rule">						<annotation>							<documentation>A list of configuration rules.</documentation>						</annotation>					</element>				</sequence>			</extension>		</complexContent>	</complexType>	<simpleType name="filtering-action">		<annotation>			<documentation>The actions for the filtering rules.</documentation>		</annotation>		<restriction base="string">			<enumeration value="accept">				<annotation>					<documentation>The ACCEPT action (accept the packet).</documentation>				</annotation>			</enumeration>			<enumeration value="drop">				<annotation>					<documentation>The DROP action (discard the packet).</documentation>				</annotation>			</enumeration>			<enumeration value="reject">				<annotation>					<documentation>The REJECT action (discard the packet and send back a destination unreachable).</documentation>				</annotation>			</enumeration>		</restriction>	</simpleType>	<simpleType name="resolution-strategy">		<annotation>			<documentation>The resolution strategies.</documentation>		</annotation>		<restriction base="string">			<enumeration value="FMR">				<annotation>					<documentation>First matching rule strategy.</documentation>				</annotation>			</enumeration>			<enumeration value="DTP">				<annotation>					<documentation>Deny take precedence strategy.</documentation>				</annotation>			</enumeration>			<enumeration value="ATP">				<annotation>					<documentation>Allow take precedence strategy.</documentation>				</annotation>			</enumeration>			<enumeration value="MSTP">				<annotation>					<documentation>Most specific take precedence strategy.</documentation>				</annotation>			</enumeration>			<enumeration value="LSTP">				<annotation>					<documentation>Least specific take precedence strategy.</documentation>				</annotation>			</enumeration>		</restriction>	</simpleType>	<complexType name="filtering-rule">		<annotation>			<documentation>A filtering rule.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="1" name="priority" type="positiveInteger">				<annotation>					<documentation>The rule priority.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="1" name="action" type="tns:filtering-action">				<annotation>					<documentation>The rule action.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="condition" type="tns:filtering-condition">				<annotation>					<documentation>The rule condition.</documentation>				</annotation>			</element>		</sequence>	</complexType>	<complexType name="filtering-condition">		<annotation>			<documentation>A filtering rule condition.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="0" name="packet-filter-condition" type="tns:packet-filter-condition">				<annotation>					<documentation>A condition on the packets.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="application-layer-condition" type="tns:application-layer-condition">				<annotation>					<documentation>A condition on the application layer.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="stateful-condition" type="tns:stateful-condition">				<annotation>					<documentation>A condition on the connection state.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="traffic-flow-condition" type="tns:traffic-flow-condition">				<annotation>					<documentation>A condition on the traffic flow.</documentation>				</annotation>			</element>		</sequence>	</complexType>	<complexType name="packet-filter-condition">		<annotation>			<documentation>A condition on the traffic packets.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="0" name="direction">				<annotation>					<documentation>The traffic direction.</documentation>				</annotation>				<simpleType>					<restriction base="string">						<enumeration value="inbound">							<annotation>								<documentation>The traffic that is received.</documentation>							</annotation>						</enumeration>						<enumeration value="outbound">							<annotation>								<documentation>The traffic that is sent.</documentation>							</annotation>						</enumeration>					</restriction>				</simpleType>			</element>			<element maxOccurs="1" minOccurs="0" name="source-address" type="tns:ip">				<annotation>					<documentation>The source IP address. It can be a single IP, a range or an IP in CIDR form.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="source-port" type="tns:port">				<annotation>					<documentation>The source port. It can be a single port number or a range.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="destination-address" type="tns:ip">				<annotation>					<documentation>The destination IP address. It can be a single IP, a range or an IP in CIDR form.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="destination-port" type="tns:port">				<annotation>					<documentation>The destination port. It can be a single port number or a range.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="interface" type="string">				<annotation>					<documentation>The interface of the rule.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="1" name="protocol">				<annotation>					<documentation>The protocol of the rule.</documentation>				</annotation>				<simpleType>					<restriction base="string">						<enumeration value="TCP"></enumeration>						<enumeration value="UDP"></enumeration>						<enumeration value="*"></enumeration>					</restriction>				</simpleType>			</element>		</sequence>	</complexType>	<simpleType name="ip">		<annotation>			<documentation>An IP. It can be a single IP, a range or an IP in CIDR form.</documentation>		</annotation>		<restriction base="string">			<pattern value="(\d+\.\d+\.\d+\.\d+(-\d+\.\d+\.\d+\.\d+)?)|(\d+\.\d+\.\d+\.\d+/\d+)|\*|any" />		</restriction>	</simpleType>	<simpleType name="port">		<annotation>			<documentation>A port. It can be a single port number or a range.</documentation>		</annotation>		<restriction base="string">			<pattern value="(\*|any|\d+(-\d+)?)" />		</restriction>	</simpleType>	<simpleType name="url">		<annotation>			<documentation>An URL.</documentation>		</annotation>		<restriction base="string">			<pattern value="(http|https)://.+(:(\*|\d+(-\d+)?))?" />		</restriction>	</simpleType>	<simpleType name="state">		<annotation>			<documentation>The state of a TCP connection.</documentation>		</annotation>		<restriction base="string">			<enumeration value="CLOSED" />			<enumeration value="LISTEN" />			<enumeration value="ESTABLISHED" />			<enumeration value="FIN-WAIT-1" />			<enumeration value="CLOSE-WAIT" />			<enumeration value="FIN-WAIT-2" />			<enumeration value="LAST-ACK" />			<enumeration value="CLOSING" />			<enumeration value="TIME-WAIT" />		</restriction>	</simpleType>	<simpleType name="method">		<annotation>			<documentation>An HTTP method.</documentation>		</annotation>		<restriction base="string">			<enumeration value="GET" />			<enumeration value="POST" />		</restriction>	</simpleType>	<complexType name="application-layer-condition">		<annotation>			<documentation>A condition on the application layer.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="0" name="url" type="tns:url">				<annotation>					<documentation>The URL.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="method" type="tns:method">				<annotation>					<documentation>The HTTP method.</documentation>				</annotation>			</element>		</sequence>	</complexType>	<complexType name="stateful-condition">		<annotation>			<documentation>A condition on the connection state.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="0" name="state" type="tns:state">				<annotation>					<documentation>The connection state.</documentation>				</annotation>			</element>		</sequence>	</complexType>	<complexType name="traffic-flow-condition">		<annotation>			<documentation>A condition on the traffic flow.</documentation>		</annotation>		<sequence>			<element maxOccurs="1" minOccurs="0" name="max-connections" type="positiveInteger">				<annotation>					<documentation>The maximum number of connections per host.</documentation>				</annotation>			</element>			<element maxOccurs="1" minOccurs="0" name="rate-limit">				<annotation>					<documentation>The rate limit for the traffic. It is a number of allowed packets or bits per unit of time (seconds, minutes, hours or days).</documentation>				</annotation>				<simpleType>					<restriction base="string">						<pattern value="\d+/(second|minute|hour|day|s|m|h|d)"></pattern>					</restriction>				</simpleType>			</element>		</sequence>	</complexType></schema>

=== shield-h2020/dashboard/backend/test/resources/input-data/mspl/ddos-mspl-multiple-vnsf.xml
<?xml version="1.0" encoding="UTF-8"?>
<mspl-set xmlns="http://security.polito.it/shield/mspl" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://security.polito.it/shield/mspl mspl.xsd ">

	<!-- TCP SYN flood (high severity) - drop the packets -->

	<context>
		 <severity>3</severity>
		 <type>DoS</type>
		 <timestamp>2017-10-17T13:32:00</timestamp>
	</context>

	<it-resource id="vNSF1">
		<configuration xsi:type="filtering-configuration">
			<default-action>accept</default-action>
			<resolution-strategy>FMR</resolution-strategy>
			<rule> <!-- for each DARE attacker/attack target pairs -->
				<priority>1</priority>
				<action>drop</action>
				<condition>
					<packet-filter-condition>
						<direction>inbound</direction>
						<!--  <source-address></source-address> --> <!-- insert DARE attacker IP here -->
						<!--  <source-port></source-port> --> <!-- insert DARE attacker ports here (if any) -->
						<!--  <destination-address></destination-address> --> <!-- insert DARE attack target IP here -->
						<!--  <destination-port></destination-port> --> <!-- insert DARE attack target port here (if any) -->
						<protocol>TCP</protocol>
					</packet-filter-condition>
				</condition>
			</rule>
		</configuration>
	</it-resource>

	<!-- TCP SYN flood (low severity) - limit the packets -->

	<it-resource id="vNSF2">
		<configuration xsi:type="filtering-configuration">
			<default-action>drop</default-action>
			<resolution-strategy>FMR</resolution-strategy>
			<rule>
				<priority>1</priority>
				<action>accept</action>
				<condition>
					<packet-filter-condition>
						<direction>inbound</direction>
						<protocol>TCP</protocol>
					</packet-filter-condition>
					<traffic-flow-condition>
						<max-connections>10</max-connections>
					</traffic-flow-condition>
				</condition>
			</rule>
			<rule> <!-- for each DARE attacker/attack target pairs -->
				<priority>2</priority>
				<action>accept</action>
				<condition>
					<packet-filter-condition>
						<direction>inbound</direction>
						<!-- <source-address></source-address> --> <!-- insert DARE attacker IP here -->
						<!-- <source-port></source-port> --> <!-- insert DARE attacker ports here (if any) -->
						<!-- <destination-address></destination-address> --> <!-- insert DARE attack target IP here -->
						<!-- <destination-port></destination-port> --> <!-- insert DARE attack target port here (if any) -->
						<protocol>TCP</protocol>
					</packet-filter-condition>
					<traffic-flow-condition>
						<rate-limit>100/s</rate-limit>
					</traffic-flow-condition>
				</condition>
			</rule>
		</configuration>
	</it-resource>

	<!-- UDP flood (high severity) - drop the datagrams -->

	<it-resource id="vNSF3">
		<configuration xsi:type="filtering-configuration">
			<default-action>accept</default-action>
			<resolution-strategy>FMR</resolution-strategy>
			<rule> <!-- for each DARE attacker/attack target pairs -->
				<priority>1</priority>
				<action>drop</action>
				<condition>
					<packet-filter-condition>
						<direction>inbound</direction>
						<!-- <source-address></source-address> --> <!-- insert DARE attacker IP here -->
						<!-- <source-port></source-port> --> <!-- insert DARE attacker ports here (if any) -->
						<!-- <destination-address></destination-address>  --> <!-- insert DARE attack target IP here -->
						<!-- <destination-port></destination-port> --> <!-- insert DARE attack target port here (if any) -->
						<protocol>UDP</protocol>
					</packet-filter-condition>
				</condition>
			</rule>
		</configuration>
	</it-resource>

	<!-- UDP flood (low severity)  - limit the datagrams -->

	<it-resource id="vNSF4">
		<configuration xsi:type="filtering-configuration">
			<default-action>drop</default-action>
			<resolution-strategy>FMR</resolution-strategy>
			<rule> <!-- for each DARE attacker/attack target pairs -->
				<priority>1</priority>
				<action>accept</action>
				<condition>
					<packet-filter-condition>
						<direction>inbound</direction>
						<!-- <source-address></source-address> --> <!-- insert DARE attacker IP here -->
						<!-- <source-port></source-port>  --> <!-- insert DARE attacker ports here (if any) -->
						<!-- <destination-address></destination-address>  --> <!-- insert DARE attack target IP here -->
						<!-- <destination-port></destination-port>  --> <!-- insert DARE attack target port here (if any) -->
						<protocol>UDP</protocol>
					</packet-filter-condition>
					<traffic-flow-condition>
						<rate-limit>100/s</rate-limit>
					</traffic-flow-condition>
				</condition>
			</rule>
		</configuration>
	</it-resource>

</mspl-set>
